default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: AGAI_01_development

test:
  <<: *default
  database: AGAI_01_test
  statement_limit: 20

production:
  <<: *default
  database: AGAI_01_production
  statement_limit: 20
